"""Build Generator from current settings — shared by main.py startup and settings router."""

from chat.generator_v2 import Generator
from config.settings import settings


def build_generator() -> Generator:
    return Generator(
        llama_server_url=settings.llama_server_url,
        local_model=settings.local_model,
        claude_api_key=settings.claude_api_key,
        claude_model=settings.claude_model,
        deepseek_api_key=settings.deepseek_api_key,
        deepseek_model=settings.deepseek_model,
        gemini_api_key=settings.gemini_api_key,
        gemini_model=settings.gemini_model,
        groq_api_key=settings.groq_api_key,
        groq_model=settings.groq_model,
        nvidia_api_key=settings.nvidia_api_key,
        nvidia_model=settings.nvidia_model,
        nvidia_url=getattr(settings, "nvidia_url", "https://integrate.api.nvidia.com/v1"),
        nvidia_deepseek_api_key=getattr(settings, "nvidia_deepseek_api_key", ""),
        nvidia_deepseek_model=getattr(settings, "nvidia_deepseek_model", "deepseek-ai/deepseek-v4-pro"),
        github_api_key=settings.github_api_key,
        github_model=settings.github_model,
        github_url=getattr(settings, "github_url", "https://models.inference.ai.azure.com"),
        github_deepseek_v3_api_key=settings.github_deepseek_v3_api_key,
        github_deepseek_v3_model=settings.github_deepseek_v3_model,
        openrouter_api_key=settings.openrouter_api_key,
        openrouter_model=settings.openrouter_model,
        openrouter_url=getattr(settings, "openrouter_url", "https://openrouter.ai/api/v1"),
        openrouter_api_deep_key=settings.openrouter_api_deep_key,
        openrouter_deep_model=settings.openrouter_deep_model,
        openrouter_url_deep=getattr(settings, "openrouter_url_deep", "https://openrouter.ai/api/v1"),
        cohere_api_key=settings.cohere_api_key,
        cohere_model=settings.cohere_model,
        cohere_url=getattr(settings, "cohere_url", "https://api.cohere.ai/compatibility/v1"),
        cloudflare_api_key=settings.cloudflare_api_key,
        cloudflare_model=settings.cloudflare_model,
        cloudflare_url=getattr(
            settings,
            "cloudflare_url",
            "https://api.cloudflare.com/client/v4/accounts/adb9fb90009a849d8bc1635194a7dbd4/ai/v1",
        ),
        cerebras_api_key=settings.cerebras_api_key,
        cerebras_model=settings.cerebras_model,
        cerebras_url=getattr(settings, "cerebras_url", "https://api.cerebras.net/v1"),
        freemodel_api_key=settings.freemodel_api_key,
        freemodel_model=settings.freemodel_model,
        freemodel_url=getattr(settings, "freemodel_url", "https://freemodel.dev/v1"),
        mode=settings.llm_mode,
        task_provider_map=settings.task_provider_map,
        custom_cloud_provider=settings.custom_cloud_provider,
        local_max_tokens=settings.local_max_tokens,
        task_ultimate_fallback_chain=getattr(settings, "task_ultimate_fallback_chain", ""),
        researchmind_cloud_url=getattr(settings, "researchmind_cloud_url", ""),
        researchmind_cloud_token=getattr(settings, "researchmind_cloud_token", ""),
        researchmind_cloud_timeout=getattr(settings, "researchmind_cloud_timeout", 120.0),
    )
