"""
Test script: Generate a PDF from sample markdown content
using the same logic as the synthesis export endpoint.
"""

import io
import re
import sys
import subprocess

# ─── First, ensure fpdf2 is installed ───────────────────────────
try:
    from fpdf import FPDF
    print("✅ fpdf2 is already installed")
except ImportError:
    print("📦 Installing fpdf2...")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "fpdf2"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print("✅ fpdf2 installed successfully")
        from fpdf import FPDF
    else:
        print(f"❌ Failed to install fpdf2: {result.stderr}")
        sys.exit(1)


# ─── PDF Footer Helper (same as export.py) ─────────────────────
def _pdf_footer(pdf):
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, f"Page {pdf.page_no()}/{{nb}}", align="C")


# ─── Generate PDF from Markdown (same logic as export.py) ──────
def generate_pdf(title: str, content: str, output_path: str):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    from datetime import datetime

    # ════════════════════════════════════════════════════════════
    # COVER PAGE
    # ════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.alias_nb_pages()

    pdf.ln(50)

    # Decorative top line
    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(1.2)
    mid_x = pdf.w / 2
    pdf.line(mid_x - 30, pdf.get_y(), mid_x + 30, pdf.get_y())
    pdf.ln(14)

    # Title
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(15, 23, 42)
    title_text = title.replace("_", " ")
    pdf.multi_cell(0, 14, title_text, align="C")
    pdf.ln(6)

    # Subtitle
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 8, "Research Synthesis Report", align="C")
    pdf.ln(14)

    # Decorative bottom line
    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(1.2)
    pdf.line(mid_x - 30, pdf.get_y(), mid_x + 30, pdf.get_y())
    pdf.ln(40)

    # Metadata
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 6, "Generated by ResearchMind VN", align="C")
    pdf.ln(5)
    pdf.cell(0, 6, datetime.now().strftime('%B %d, %Y at %H:%M'), align="C")
    pdf.ln(5)
    pdf.cell(0, 6, "ResearchMind VN — AI-Powered Research Assistant", align="C")

    # Page break after cover
    pdf.add_page()

    # ════════════════════════════════════════════════════════════
    # CONTENT PAGES — Multi-line state machine parser
    # ════════════════════════════════════════════════════════════
    pdf.set_text_color(30, 30, 30)
    lines = content.split("\n")
    i = 0
    n = len(lines)

    def _render_paragraph(pdf_obj, text: str):
        clean = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
        clean = re.sub(r"\*(.+?)\*", r"\1", clean)
        pdf_obj.set_font("Helvetica", "", 10)
        pdf_obj.set_text_color(30, 30, 30)
        pdf_obj.multi_cell(0, 6, clean)

    def _render_code_block(pdf_obj, code_lines: list[str], lang: str):
        line_h = 5
        x0 = pdf_obj.l_margin
        y0 = pdf_obj.get_y()
        code_w = pdf_obj.w - pdf_obj.l_margin - pdf_obj.r_margin
        padding = 3
        x_start = x0 + padding
        y_start = y0 + padding

        total_lines = max(len(code_lines), 1)
        block_h = total_lines * line_h + 2 * padding + 2

        if y0 + block_h > pdf_obj.h - 20:
            pdf_obj.add_page()
            y0 = pdf_obj.get_y()
            y_start = y0 + padding

        pdf_obj.set_fill_color(241, 245, 249)
        pdf_obj.set_draw_color(203, 213, 225)
        pdf_obj.rect(x0, y0, code_w, block_h, style="DF")

        if lang:
            pdf_obj.set_font("Helvetica", "I", 7)
            pdf_obj.set_text_color(148, 163, 184)
            pdf_obj.set_xy(x_start + 1, y_start)
            pdf_obj.cell(0, 4, lang)
            y_start += 4

        pdf_obj.set_font("Courier", "", 8)
        pdf_obj.set_text_color(30, 41, 59)
        pdf_obj.set_xy(x_start, y_start)
        for code_line in code_lines:
            display_line = code_line.replace("\t", "    ")
            pdf_obj.cell(0, line_h, display_line)
            pdf_obj.set_x(x_start)

        pdf_obj.set_y(y_start + len(code_lines) * line_h + padding)
        pdf_obj.ln(2)

    def _render_table(pdf_obj, rows: list[list[str]]):
        if len(rows) < 2:
            return

        header_row = rows[0]
        data_rows = rows[2:] if len(rows) > 2 else []

        n_cols = len(header_row)
        if n_cols == 0:
            return

        avail_w = pdf_obj.w - pdf_obj.l_margin - pdf_obj.r_margin
        col_w = avail_w / n_cols
        cell_h = 7
        header_h = cell_h
        data_h = len(data_rows) * cell_h
        total_h = header_h + data_h + 2

        y0 = pdf_obj.get_y()
        if y0 + total_h > pdf_obj.h - 20:
            pdf_obj.add_page()
            y0 = pdf_obj.get_y()

        x0 = pdf_obj.l_margin
        pdf_obj.set_font("Helvetica", "B", 9)
        pdf_obj.set_fill_color(99, 102, 241)
        pdf_obj.set_text_color(255, 255, 255)
        pdf_obj.set_draw_color(99, 102, 241)
        pdf_obj.set_xy(x0, y0)
        for ci, hcell in enumerate(header_row):
            pdf_obj.cell(col_w, cell_h, hcell.strip(), border=1, fill=True, align="C")
        pdf_obj.ln(cell_h)

        pdf_obj.set_font("Helvetica", "", 9)
        pdf_obj.set_text_color(30, 30, 30)
        pdf_obj.set_draw_color(203, 213, 225)
        for ri, row in enumerate(data_rows):
            if ri % 2 == 0:
                pdf_obj.set_fill_color(248, 250, 252)
            else:
                pdf_obj.set_fill_color(255, 255, 255)
            pdf_obj.set_xy(x0, pdf_obj.get_y())
            for ci, dcell in enumerate(row):
                pdf_obj.cell(col_w, cell_h, dcell.strip(), border=1, fill=True, align="C")
            pdf_obj.ln(cell_h)

        pdf_obj.ln(3)

    while i < n:
        stripped = lines[i].strip()

        # ── Code block ──
        if stripped.startswith("```"):
            lang = stripped[3:].strip()
            code_lines = []
            i += 1
            while i < n and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i].rstrip())
                i += 1
            i += 1  # Skip closing ```
            _render_code_block(pdf, code_lines, lang)
            continue

        # ── Table ──
        if stripped.startswith("|") and "|" in stripped[1:]:
            table_rows = []
            while i < n and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().split("|")]
                cells = [c for c in cells if c]
                table_rows.append(cells)
                i += 1
            _render_table(pdf, table_rows)
            continue

        if not stripped:
            i += 1
            continue

        if stripped.startswith("# "):
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(15, 23, 42)
            pdf.multi_cell(0, 10, stripped[2:])
            pdf.ln(2)
            i += 1
            continue

        if stripped.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 8, stripped[3:])
            pdf.ln(1)
            i += 1
            continue

        if stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(51, 65, 85)
            pdf.multi_cell(0, 7, stripped[4:])
            pdf.ln(1)
            i += 1
            continue

        if stripped.startswith("---"):
            pdf.set_draw_color(200, 200, 200)
            pdf.set_line_width(0.3)
            pdf.line(pdf.l_margin, pdf.get_y() + 2, pdf.w - pdf.r_margin, pdf.get_y() + 2)
            pdf.ln(6)
            i += 1
            continue

        if stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            text = stripped[2:]
            pdf.cell(6, 6, chr(8226))
            pdf.multi_cell(0, 6, text)
            i += 1
            continue

        if re.match(r"^\d+\.\s+", stripped):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, stripped)
            i += 1
            continue

        if stripped.startswith("> "):
            pdf.set_x(pdf.l_margin + 4)
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(71, 85, 105)
            y_start = pdf.get_y()
            pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 8, 6, stripped[2:])
            y_end = pdf.get_y()
            pdf.set_draw_color(139, 92, 246)
            pdf.set_line_width(0.8)
            pdf.line(pdf.l_margin, y_start, pdf.l_margin, y_end)
            pdf.set_text_color(30, 30, 30)
            i += 1
            continue

        _render_paragraph(pdf, stripped)
        i += 1

    pdf.footer = lambda: _pdf_footer(pdf)
    pdf.output(output_path)
    return output_path


# ─── Test with rich sample markdown ────────────────────────────
if __name__ == "__main__":
    sample_markdown = """# Synthesis Report
*Model: gemini-2.0-flash*

## Overview
This is a **sample synthesis report** generated to test the enhanced *PDF export* with cover page, code blocks, and tables.

### Key Findings
- Research shows significant improvement in model performance
- The proposed method achieves **95% accuracy** on benchmark datasets
- Multiple datasets were used for comprehensive evaluation

> This finding strongly supports the main hypothesis of the study and aligns with prior work.

---

## Code Implementation

The main training loop is implemented as follows:

```python
import torch
import torch.nn as nn

class ResearchModel(nn.Module):
    def __init__(self, vocab_size, hidden_dim=768):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, hidden_dim)
        self.transformer = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(hidden_dim, nhead=12),
            num_layers=6
        )

    def forward(self, x):
        return self.transformer(self.embed(x))
```

To run inference:

```bash
python train.py --epochs 10 --batch-size 32 --lr 2e-5
```

---

## Experimental Results

The table below summarizes the quantitative results across all evaluation metrics.

### Benchmark Comparison
| Model | Accuracy | F1 Score | Precision | Recall |
|-------|----------|----------|-----------|--------|
| Ours | 94.2% | 0.937 | 0.945 | 0.931 |
| Baseline A | 89.1% | 0.882 | 0.891 | 0.874 |
| Baseline B | 91.5% | 0.908 | 0.914 | 0.902 |
| SOTA 2024 | 93.8% | 0.931 | 0.938 | 0.925 |

Our method outperforms all baselines across every metric, with a 2.7% improvement over the previous state-of-the-art.

---

## Ablation Study

```
Component          | Acc    | Delta
-------------------|--------|-------
Full model        | 94.2%  |  —
w/o attention     | 88.3%  | -5.9%
w/o pretraining   | 90.1%  | -4.1%
w/o data aug      | 92.7%  | -1.5%
```

> "The attention mechanism contributes the most to overall performance."

## Conclusion

This work presents a novel approach to the problem. Key contributions include:

1. A novel architecture combining transformers with retrieval augmentation
2. Comprehensive evaluation on 5 benchmark datasets
3. State-of-the-art results with **94.2% accuracy**
4. Open-source release of code and pre-trained models

Future work will explore:
* Scaling to larger model sizes
* Multi-modal extension with vision encoders
* Real-time deployment optimization

---

*This enhanced test document validates cover page, code blocks, and table rendering in the PDF export.*
"""

    output_path = "test_synthesis_report.pdf"
    try:
        result = generate_pdf("Enhanced_Synthesis_Report_Test", sample_markdown, output_path)
        size = __import__('os').path.getsize(output_path)
        print(f"\n✅ PDF generated successfully: {output_path}")
        print(f"   File size: {size} bytes ({size/1024:.1f} KB)")
        print(f"   Location: {__import__('os').path.abspath(output_path)}")
    except Exception as e:
        print(f"\n❌ PDF generation failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
