"""
Test ALL 3 export formats (HTML/DOCX/PDF) with a single sample markdown.
Runs all tests and reports results at the end.
"""

import sys
import os
import traceback
from datetime import datetime

# Add backend to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "backend"))

# ─── Rich sample markdown with all supported features ──────────
SAMPLE_MD = r"""# Research Synthesis Report
*Model: gemini-2.0-flash | Date: March 2025*

## Overview
This document tests **all three export formats** (HTML, DOCX, PDF) with *every* supported markdown feature including `inline code`.

### Key Findings
- Code blocks with **syntax highlighting labels** are supported
- Tables render with **purple headers** and alternating rows
- Blockquotes show a *purple left border* accent
- Horizontal rules separate sections cleanly

> This is a blockquote with **bold** and *italic* text to verify inline formatting.

---

## Code Implementation

The core training loop:

```python
import torch
import torch.nn as nn

class TransformerModel(nn.Module):
    def __init__(self, d_model=512, nhead=8):
        super().__init__()
        self.attention = nn.MultiheadAttention(d_model, nhead)
        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_model * 4),
            nn.ReLU(),
            nn.Linear(d_model * 4, d_model)
        )

    def forward(self, x):
        attn_out, _ = self.attention(x, x, x)
        return self.ffn(attn_out)
```

For training:

```bash
python train.py \
  --epochs 50 \
  --batch-size 64 \
  --lr 1e-4 \
  --use-mixed-precision
```

---

## Experimental Results

### Benchmark Comparison
| Model | Accuracy | F1 Score | Precision | Recall |
|-------|----------|----------|-----------|--------|
| **Ours** | **94.2%** | **0.937** | **0.945** | **0.931** |
| Baseline A | 89.1% | 0.882 | 0.891 | 0.874 |
| Baseline B | 91.5% | 0.908 | 0.914 | 0.902 |
| SOTA 2024 | 93.8% | 0.931 | 0.938 | 0.925 |

### Ablation Study
| Configuration | Accuracy | Δ |
|--------------|----------|---|
| Full model | 94.2% | — |
| w/o attention | 88.3% | -5.9% |
| w/o pretraining | 90.1% | -4.1% |
| w/o data augmentation | 92.7% | -1.5% |

> Attention contributes **most** to performance (5.9% drop without it).
> Pretraining also provides a significant boost of *4.1%*.

---

## Conclusion
This research demonstrates a novel approach with three key contributions:

1. **Novel architecture** combining transformers with retrieval
2. **State-of-the-art** performance across 5 benchmarks
3. **Open-source** release of all code and models

The `train.py` script supports distributed training across multiple GPUs.

Future work will explore:
* Scaling to larger model sizes (e.g., 7B parameters)
* Multi-modal extension with vision encoders
* Real-time deployment optimization for edge devices

---

*Generated by ResearchMind VN — AI-Powered Research Assistant*
"""


# ═══════════════════════════════════════════════════════════════
# HTML TEST
# ═══════════════════════════════════════════════════════════════
def test_html(output_dir="."):
    """Test HTML export using _md_to_html() from export.py"""
    try:
        from export import _md_to_html, _escape_html
        html_body = _md_to_html(SAMPLE_MD)

        html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<title>Research Synthesis Report — ResearchMind VN</title>
<style>
  body {{ font-family: -apple-system, sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1e293b; background: #f8fafc; }}
  .container {{ background: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); border: 1px solid #e2e8f0; }}
  h1 {{ border-bottom: 2px solid #8b5cf6; padding-bottom: 12px; color: #0f172a; }}
  h2 {{ color: #1e293b; margin-top: 32px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }}
  h3 {{ color: #334155; margin-top: 24px; }}
  p {{ margin-bottom: 1.25em; }}
  ul, ol {{ padding-left: 20px; margin-bottom: 1.25em; }}
  li {{ margin-bottom: 0.5em; }}
  code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; font-family: Consolas, monospace; }}
  pre {{ background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px 20px; overflow-x: auto; margin: 0 0 1.25em 0; }}
  pre code {{ background: none; padding: 0; border-radius: 0; font-size: 0.82em; line-height: 1.5; display: block; white-space: pre; }}
  blockquote {{ border-left: 4px solid #8b5cf6; background: #f8fafc; margin: 0 0 1.25em 0; padding: 12px 20px; color: #475569; font-style: italic; }}
  hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 32px 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 0 0 1.25em 0; font-size: 0.9em; }}
  table thead {{ background: #6366f1; color: #fff; }}
  table th {{ padding: 10px 12px; text-align: center; font-weight: 600; }}
  table td {{ padding: 8px 12px; text-align: center; border-bottom: 1px solid #e2e8f0; color: #334155; }}
  table tbody tr:nth-child(even) {{ background: #f8fafc; }}
  table tbody tr:hover {{ background: #f1f5f9; }}
  .footer {{ margin-top: 60px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.85em; color: #64748b; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  {html_body}
  <div class="footer">Generated by ResearchMind VN — {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
</div>
</body>
</html>"""

        path = os.path.join(output_dir, "test_all_exports.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html_doc)
        return True, path
    except Exception as e:
        return False, str(e)


# ═══════════════════════════════════════════════════════════════
# DOCX TEST
# ═══════════════════════════════════════════════════════════════
def test_docx(output_dir="."):
    """Test DOCX export using python-docx + shared parser"""
    try:
        from docx import Document
        from docx.shared import Pt, Cm, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        from export import _parse_md_events, _add_formatted_text

        doc = Document()
        style = doc.styles["Normal"]
        style.font.name = "Times New Roman"
        style.font.size = Pt(12)
        style.paragraph_format.line_spacing = 1.5
        style.paragraph_format.space_after = Pt(6)

        title_para = doc.add_heading("Research Synthesis Report", level=1)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()

        def _code_block(code_lines, lang):
            if lang:
                lp = doc.add_paragraph()
                lr = lp.add_run(lang)
                lr.font.size = Pt(8)
                lr.font.color.rgb = RGBColor(0x94, 0xa3, 0xb8)
                lr.italic = True
                lp.paragraph_format.space_after = Pt(2)
                lp.paragraph_format.space_before = Pt(4)
            for cl in code_lines:
                cp = doc.add_paragraph()
                cr = cp.add_run(cl.replace("\t", "    ") if cl else " ")
                cr.font.name = "Consolas"
                cr.font.size = Pt(8.5)
                cp.paragraph_format.space_after = Pt(0)
                cp.paragraph_format.space_before = Pt(0)
                cp.paragraph_format.line_spacing = 1.15
                shd = OxmlElement('w:shd')
                shd.set(qn('w:fill'), 'f1f5f9')
                shd.set(qn('w:val'), 'clear')
                cp.paragraph_format.element.get_or_add_pPr().append(shd)

        def _table(rows):
            if len(rows) < 2: return
            header_row = rows[0]
            data_rows = rows[2:] if len(rows) > 2 else []
            if not header_row: return
            table = doc.add_table(rows=1 + len(data_rows), cols=len(header_row))
            table.style = 'Table Grid'
            for ci, hcell in enumerate(header_row):
                cell = table.rows[0].cells[ci]
                cell.text = hcell.strip()
                for para in cell.paragraphs:
                    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    for run in para.runs:
                        run.bold = True
                        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                        run.font.size = Pt(10)
                shd = OxmlElement('w:shd')
                shd.set(qn('w:fill'), '6366f1')
                shd.set(qn('w:val'), 'clear')
                cell._tc.get_or_add_tcPr().append(shd)
            alt = ['f8fafc', 'ffffff']
            for ri, row in enumerate(data_rows):
                for ci, dcell in enumerate(row):
                    cell = table.rows[ri + 1].cells[ci]
                    cell.text = dcell.strip()
                    for para in cell.paragraphs:
                        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                        for run in para.runs:
                            run.font.size = Pt(10)
                    shd = OxmlElement('w:shd')
                    shd.set(qn('w:fill'), alt[ri % 2])
                    shd.set(qn('w:val'), 'clear')
                    cell._tc.get_or_add_tcPr().append(shd)
            doc.add_paragraph()

        for event, data in _parse_md_events(SAMPLE_MD):
            if event == "code_block": _code_block(data[0], data[1])
            elif event == "table": _table(data[0])
            elif event == "heading1": doc.add_heading(data[0], level=1)
            elif event == "heading2": doc.add_heading(data[0], level=2)
            elif event == "heading3": doc.add_heading(data[0], level=3)
            elif event == "hr":
                p = doc.add_paragraph()
                pPr = p.paragraph_format.element.get_or_add_pPr()
                pBdr = OxmlElement('w:pBdr')
                bottom = OxmlElement('w:bottom')
                bottom.set(qn('w:val'), 'single')
                bottom.set(qn('w:sz'), '6')
                bottom.set(qn('w:space'), '4')
                bottom.set(qn('w:color'), 'cbd5e1')
                pBdr.append(bottom)
                pPr.append(pBdr)
            elif event == "bullet_list":
                for item in data[0]:
                    p = doc.add_paragraph(style='List Bullet')
                    _add_formatted_text(p, item)
            elif event == "numbered_list":
                for item in data[0]:
                    p = doc.add_paragraph(style='List Number')
                    _add_formatted_text(p, item)
            elif event == "blockquote":
                for line in data[0]:
                    p = doc.add_paragraph(style='Quote')
                    _add_formatted_text(p, line)
            elif event == "paragraph":
                for line in data[0]:
                    p = doc.add_paragraph()
                    _add_formatted_text(p, line)

        doc.add_paragraph()
        fp = doc.add_paragraph()
        fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        fr = fp.add_run(f"Generated by ResearchMind VN on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        fr.font.size = Pt(9)
        fr.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        for section in doc.sections:
            section.top_margin = Cm(2.54)
            section.bottom_margin = Cm(2.54)
            section.left_margin = Cm(2.54)
            section.right_margin = Cm(2.54)

        path = os.path.join(output_dir, "test_all_exports.docx")
        doc.save(path)
        return True, path
    except Exception as e:
        return False, str(e)


# ═══════════════════════════════════════════════════════════════
# PDF TEST
# ═══════════════════════════════════════════════════════════════
def test_pdf(output_dir="."):
    """Test PDF export using fpdf2 + shared parser"""
    try:
        from fpdf import FPDF
        from export import _parse_md_events

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)

        # Cover page
        pdf.add_page()
        pdf.alias_nb_pages()
        pdf.ln(50)
        pdf.set_draw_color(99, 102, 241)
        pdf.set_line_width(1.2)
        mid_x = pdf.w / 2
        pdf.line(mid_x - 30, pdf.get_y(), mid_x + 30, pdf.get_y())
        pdf.ln(14)
        pdf.set_font("Helvetica", "B", 28)
        pdf.set_text_color(15, 23, 42)
        title_text = "Research Synthesis Report"
        pdf.multi_cell(0, 14, title_text, align="C")
        pdf.ln(6)
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 8, "Research Synthesis Report", align="C")
        pdf.ln(14)
        pdf.set_draw_color(99, 102, 241)
        pdf.set_line_width(1.2)
        pdf.line(mid_x - 30, pdf.get_y(), mid_x + 30, pdf.get_y())
        pdf.ln(40)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 6, "Generated by ResearchMind VN", align="C")
        pdf.ln(5)
        pdf.cell(0, 6, datetime.now().strftime('%B %d, %Y at %H:%M'), align="C")
        pdf.ln(5)
        pdf.cell(0, 6, "ResearchMind VN — AI-Powered Research Assistant", align="C")
        pdf.add_page()

        # Content pages
        pdf.set_text_color(30, 30, 30)

        def _strip(text):
            import re
            return re.sub(r"\*\*(.+?)\*\*", r"\1", re.sub(r"\*(.+?)\*", r"\1", text))

        def _code_block(code_lines, lang):
            line_h = 5
            x0 = pdf.l_margin
            y0 = pdf.get_y()
            code_w = pdf.w - pdf.l_margin - pdf.r_margin
            padding = 3
            lang_h = 4 if lang else 0
            xs = x0 + padding
            ys = y0 + padding
            total_lines = max(len(code_lines), 1)
            block_h = total_lines * line_h + 2 * padding + 2 + lang_h
            if y0 + block_h > pdf.h - 20:
                pdf.add_page()
                y0 = pdf.get_y()
                ys = y0 + padding
            pdf.set_fill_color(241, 245, 249)
            pdf.set_draw_color(203, 213, 225)
            pdf.rect(x0, y0, code_w, block_h, style="DF")
            if lang:
                pdf.set_font("Helvetica", "I", 7)
                pdf.set_text_color(148, 163, 184)
                pdf.set_xy(xs + 1, ys)
                pdf.cell(0, 4, lang)
                ys += lang_h
            pdf.set_font("Courier", "", 8)
            pdf.set_text_color(30, 41, 59)
            pdf.set_xy(xs, ys)
            for cl in code_lines:
                pdf.cell(0, line_h, cl.replace("\t", "    "))
                pdf.set_x(xs)
            pdf.set_y(ys + len(code_lines) * line_h + padding)
            pdf.ln(2)

        def _table(rows):
            if len(rows) < 2: return
            header = rows[0]
            data_rows = rows[2:] if len(rows) > 2 else []
            n_cols = len(header)
            if n_cols == 0: return
            col_w = (pdf.w - pdf.l_margin - pdf.r_margin) / n_cols
            ch = 7
            y0 = pdf.get_y()
            if y0 + (ch * (1 + len(data_rows)) + 2) > pdf.h - 20:
                pdf.add_page()
                y0 = pdf.get_y()
            x0 = pdf.l_margin
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(99, 102, 241)
            pdf.set_text_color(255, 255, 255)
            pdf.set_draw_color(99, 102, 241)
            pdf.set_xy(x0, y0)
            for hc in header:
                pdf.cell(col_w, ch, hc.strip(), border=1, fill=True, align="C")
            pdf.ln(ch)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(30, 30, 30)
            pdf.set_draw_color(203, 213, 225)
            for ri, row in enumerate(data_rows):
                pdf.set_fill_color(248, 250, 252) if ri % 2 == 0 else pdf.set_fill_color(255, 255, 255)
                pdf.set_xy(x0, pdf.get_y())
                for dc in row:
                    pdf.cell(col_w, ch, dc.strip(), border=1, fill=True, align="C")
                pdf.ln(ch)
            pdf.ln(3)

        for event, data in _parse_md_events(SAMPLE_MD):
            if event == "code_block": _code_block(data[0], data[1])
            elif event == "table": _table(data[0])
            elif event == "heading1":
                pdf.set_font("Helvetica", "B", 16)
                pdf.set_text_color(15, 23, 42)
                pdf.multi_cell(0, 10, _strip(data[0]))
                pdf.ln(2)
            elif event == "heading2":
                pdf.set_font("Helvetica", "B", 13)
                pdf.set_text_color(30, 41, 59)
                pdf.multi_cell(0, 8, _strip(data[0]))
                pdf.ln(1)
            elif event == "heading3":
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(51, 65, 85)
                pdf.multi_cell(0, 7, _strip(data[0]))
                pdf.ln(1)
            elif event == "hr":
                pdf.set_draw_color(200, 200, 200)
                pdf.set_line_width(0.3)
                pdf.line(pdf.l_margin, pdf.get_y() + 2, pdf.w - pdf.r_margin, pdf.get_y() + 2)
                pdf.ln(6)
            elif event == "bullet_list":
                for item in data[0]:
                    pdf.set_font("Helvetica", "", 10)
                    pdf.set_text_color(30, 30, 30)
                    pdf.cell(6, 6, chr(8226))
                    pdf.multi_cell(0, 6, _strip(item))
            elif event == "numbered_list":
                for idx, item in enumerate(data[0], 1):
                    pdf.set_font("Helvetica", "", 10)
                    pdf.set_text_color(30, 30, 30)
                    pdf.multi_cell(0, 6, f"{idx}. {_strip(item)}")
            elif event == "blockquote":
                for line in data[0]:
                    pdf.set_x(pdf.l_margin + 4)
                    pdf.set_font("Helvetica", "I", 10)
                    pdf.set_text_color(71, 85, 105)
                    ys = pdf.get_y()
                    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 8, 6, line if line else " ")
                    pdf.set_draw_color(139, 92, 246)
                    pdf.set_line_width(0.8)
                    pdf.line(pdf.l_margin, ys, pdf.l_margin, pdf.get_y())
                    pdf.set_text_color(30, 30, 30)
            elif event == "paragraph":
                for line in data[0]:
                    pdf.set_font("Helvetica", "", 10)
                    pdf.set_text_color(30, 30, 30)
                    pdf.multi_cell(0, 6, _strip(line))

        def _footer(p):
            p.set_y(-15)
            p.set_font("Helvetica", "I", 8)
            p.set_text_color(150, 150, 150)
            p.cell(0, 10, f"Page {p.page_no()}/{{nb}}", align="C")
        pdf.footer = lambda: _footer(pdf)

        path = os.path.join(output_dir, "test_all_exports.pdf")
        pdf.output(path)
        return True, path
    except Exception as e:
        return False, str(e)


# ═══════════════════════════════════════════════════════════════
# MAIN — Run all tests
# ═══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    output_dir = "."
    results = {}

    print("═" * 60)
    print("  ResearchMind VN — ALL FORMATS EXPORT TEST")
    print("═" * 60)

    # HTML
    print("\n📄 Testing HTML export...", end=" ")
    ok, path = test_html(output_dir)
    results["HTML"] = ok
    if ok:
        size = os.path.getsize(path)
        print(f"✅  ({size/1024:.1f} KB) → {os.path.basename(path)}")
    else:
        print(f"❌  FAILED: {path}")

    # DOCX
    print("📄 Testing DOCX export...", end=" ")
    ok, path = test_docx(output_dir)
    results["DOCX"] = ok
    if ok:
        size = os.path.getsize(path)
        print(f"✅  ({size/1024:.1f} KB) → {os.path.basename(path)}")
    else:
        print(f"❌  FAILED: {path}")

    # PDF
    print("📄 Testing PDF export...", end=" ")
    ok, path = test_pdf(output_dir)
    results["PDF"] = ok
    if ok:
        size = os.path.getsize(path)
        print(f"✅  ({size/1024:.1f} KB) → {os.path.basename(path)}")
    else:
        print(f"❌  FAILED: {path}")

    # Summary
    print("\n" + "─" * 60)
    passed = sum(1 for v in results.values() if v)
    total = len(results)
    print(f"  Result: {passed}/{total} formats passed")
    if passed == total:
        print("  ✅ ALL FORMATS GENERATED SUCCESSFULLY!")
        print("\n  Files created:")
        for fmt in ["HTML", "DOCX", "PDF"]:
            print(f"    • test_all_exports.{fmt.lower()}")
        print("\n  📖 Open test_all_exports.html in a browser")
        print("  📖 Open test_all_exports.docx in Word")
        print("  📖 Open test_all_exports.pdf in a PDF viewer")
    else:
        failed = [k for k, v in results.items() if not v]
        print(f"  ❌ Failed formats: {', '.join(failed)}")
    print("─" * 60)
