export const APP_CONFIG = {
  name: "ResearchMind",
  productName: "ResearchMind Cloud",
  tagline: "Local-first research power + cloud collaboration",
  version: "1.0.0",
  supportEmail: "support@researchmind.app",
  githubUrl: "https://github.com/ViuGiaLai/researchmind",
  docsUrl: "https://researchmind.pages.dev/docs.html",
  marketingUrl: "https://researchmind.pages.dev",
  cloudUrl: "https://researchmind.pages.dev",
  apiVersion: "v1",
  maxUploadMb: 100,
  defaultLocale: "en" as const,
  locales: ["en", "vi"] as const,
} as const;

export const API_PATHS = {
  workspaces: "/workspaces",
  reports: "/reports",
  snapshots: "/snapshots",
  activity: "/activity",
  backups: "/backups",
  notifications: "/notifications",
  devices: "/devices",
  billing: "/billing",
  settings: "/settings",
  analytics: "/analytics",
  apiKeys: "/api-keys",
  me: "/me",
} as const;

export const ROUTES = {
  home: "/",
  pricing: "/pricing",
  about: "/about",
  download: "/download",
  blog: "/blog",
  docs: "/docs",
  changelog: "/changelog",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  dashboard: "/app",
  workspace: "/app/workspaces",
  workspaceDetail: "/app/workspaces/:id",
  reports: "/app/reports",
  reportViewer: "/r/:id",
  snapshots: "/app/snapshots",
  activity: "/app/activity",
  analytics: "/app/analytics",
  notifications: "/app/notifications",
  backups: "/app/backups",
  devices: "/app/devices",
  team: "/app/team",
  billing: "/app/billing",
  settings: "/app/settings",
  profile: "/app/profile",
  apiKeys: "/app/api-keys",
  help: "/app/help",
  feedback: "/app/feedback",
  notFound: "*",
} as const;

export const PLAN_LIMITS = {
  free: { workspaces: 1, reports: 5, storageMb: 50, teamMembers: 1 },
  pro: { workspaces: 10, reports: 100, storageMb: 2048, teamMembers: 5 },
  lab: { workspaces: 50, reports: 1000, storageMb: 20480, teamMembers: 25 },
  enterprise: { workspaces: -1, reports: -1, storageMb: -1, teamMembers: -1 },
} as const;
