"""
ResearchMind VN — Enterprise Rule-Based Venue Engine (v5.0 with Provenance & Versioning).

Supports specific top-tier conferences & journals (CVPR, NeurIPS, ACM CHI, Nature MI, IEEE TNNLS)
with full rule versioning, last_updated timestamps, and official guideline provenance.
"""

from typing import Any

PUBLISHING_TEMPLATES: dict[str, dict[str, Any]] = {
    "cvpr": {
        "id": "cvpr",
        "name": "IEEE/CVF CVPR 2025 (Computer Vision & Pattern Recognition)",
        "venue_code": "CVPR",
        "publisher": "IEEE / CVF",
        "version": "2025.1",
        "last_updated": "2025-01-15",
        "provenance": "IEEE/CVF CVPR 2025 Author Guidelines & Formatting Manual",
        "submission_layout": "Double-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": 8,
            "word_limit": 6000,
            "max_abstract_words": 250,
        },
        "review_policy": "double_blind",
        "supported_citation_styles": ["IEEE (numeric [1])"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Methodology", "Method", "Methods", "Proposed Method", "Approach"],
                ["Experiments", "Experimental Setup", "Results", "Evaluation"],
                ["Conclusion", "Concluding Remarks"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": False,
            "requires_ccs": False,
            "requires_orcid": False,
            "requires_data_availability": False,
            "requires_funding_statement": False,
            "requires_conflict_of_interest": False,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "cvpr",
    },
    "neurips": {
        "id": "neurips",
        "name": "NeurIPS 2025 (Neural Information Processing Systems)",
        "venue_code": "NeurIPS",
        "publisher": "NeurIPS Foundation",
        "version": "2025.1",
        "last_updated": "2025-02-01",
        "provenance": "NeurIPS 2025 Call for Papers & Formatting Instructions",
        "submission_layout": "Single-column",
        "camera_ready_layout": "Single-column",
        "constraints": {
            "page_limit": 9,
            "word_limit": 7000,
            "max_abstract_words": 250,
        },
        "review_policy": "double_blind",
        "supported_citation_styles": ["NeurIPS Author-Year / Numeric"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Method", "Methods", "Methodology", "Approach"],
                ["Experiments", "Results", "Evaluation"],
                ["Conclusion", "Limitations", "Broader Impact"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": False,
            "requires_orcid": False,
            "requires_data_availability": True,
            "requires_ethics_statement": True,
            "requires_funding_statement": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "neurips_2025",
    },
    "acm_chi": {
        "id": "acm_chi",
        "name": "ACM CHI 2025 (Human Factors in Computing Systems)",
        "venue_code": "CHI",
        "publisher": "ACM",
        "version": "2025.2",
        "last_updated": "2025-01-10",
        "provenance": "ACM CHI 2025 Publication Guidelines & acmart",
        "submission_layout": "Single-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": 10000,
            "max_abstract_words": 150,
        },
        "review_policy": "double_blind",
        "supported_citation_styles": ["ACM Reference Format"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Related Work", "Background"],
                ["Method", "System Architecture", "Study Design"],
                ["Findings", "Results", "Evaluation"],
                ["Discussion", "Conclusion"],
                ["References", "Bibliography"],
            ],
            "optional_sections": [],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": True,
            "requires_orcid": True,
            "requires_data_availability": False,
            "requires_conflict_of_interest": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "acmart",
    },
    "nature_mi": {
        "id": "nature_mi",
        "name": "Nature Machine Intelligence",
        "venue_code": "NatMachIntell",
        "publisher": "Nature Portfolio / NPG",
        "version": "2025.1",
        "last_updated": "2025-01-05",
        "provenance": "Nature Machine Intelligence Guide to Authors",
        "submission_layout": "Single-column",
        "camera_ready_layout": "Single-column",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": 4500,
            "max_abstract_words": 150,
        },
        "review_policy": "single_blind",
        "supported_citation_styles": ["Nature (superscript numbers)"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Results", "Main Text"],
                ["Discussion", "Conclusion"],
                ["Methods", "Methodology"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": False,
            "requires_ccs": False,
            "requires_orcid": True,
            "requires_data_availability": True,
            "requires_ethics_statement": True,
            "requires_funding_statement": True,
            "requires_author_contributions": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "sn-jnl",
    },
    "ieee_tnnls": {
        "id": "ieee_tnnls",
        "name": "IEEE Transactions on Neural Networks and Learning Systems (TNNLS)",
        "venue_code": "TNNLS",
        "publisher": "IEEE",
        "version": "2025.1",
        "last_updated": "2025-01-01",
        "provenance": "IEEE CIS TNNLS Information for Authors 2025",
        "submission_layout": "Double-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": 12,
            "word_limit": 8000,
            "max_abstract_words": 200,
        },
        "review_policy": "single_blind",
        "supported_citation_styles": ["IEEE (numeric [1])"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["System Model", "Methodology", "Method", "Proposed Approach"],
                ["Experimental Results", "Experiments", "Performance Analysis"],
                ["Conclusion", "Concluding Remarks"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": False,
            "requires_orcid": True,
            "requires_data_availability": False,
            "requires_funding_statement": True,
            "requires_conflict_of_interest": False,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "IEEEtran",
    },
    "ieee_trans": {
        "id": "ieee_trans",
        "name": "IEEE Journal / Transactions (General Template)",
        "venue_code": "IEEE-GENERIC",
        "publisher": "IEEE",
        "version": "2025.1",
        "last_updated": "2025-01-01",
        "provenance": "IEEE Author Center Formatting Guidelines 2025",
        "submission_layout": "Double-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": 8000,
            "max_abstract_words": 250,
        },
        "review_policy": "single_blind",
        "supported_citation_styles": ["IEEE (numeric [1])"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Methodology", "Method", "Methods", "Approach", "Proposed Approach"],
                ["Experiments", "Experimental Setup", "Results", "Evaluation"],
                ["Conclusion", "Concluding Remarks"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": False,
            "requires_orcid": True,
            "requires_data_availability": False,
            "requires_funding_statement": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "IEEEtran",
    },
    "acm": {
        "id": "acm",
        "name": "ACM Conference (General acmart)",
        "venue_code": "ACM-GENERIC",
        "publisher": "ACM",
        "version": "2025.1",
        "last_updated": "2025-01-01",
        "provenance": "ACM Primary Article Template Guidelines (acmart 2025)",
        "submission_layout": "Single-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": "venue_defined",
            "max_abstract_words": 200,
        },
        "review_policy": "double_blind",
        "supported_citation_styles": ["ACM Reference Format"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Methodology", "Method", "System Architecture", "Approach"],
                ["Evaluation", "Results", "Experiments", "Performance Analysis"],
                ["Conclusion", "Concluding Remarks"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": True,
            "requires_orcid": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "acmart",
    },
    "elsevier": {
        "id": "elsevier",
        "name": "Elsevier Journal (General elsarticle)",
        "venue_code": "ELSEVIER-GENERIC",
        "publisher": "Elsevier",
        "version": "2025.1",
        "last_updated": "2025-01-01",
        "provenance": "Elsevier Guide for Authors & elsarticle Package",
        "submission_layout": "Single-column",
        "camera_ready_layout": "Double-column",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": 7500,
            "max_abstract_words": 250,
        },
        "review_policy": "single_blind",
        "supported_citation_styles": ["Elsevier Numbered", "Elsevier Harvard"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Material and methods", "Methodology", "Method"],
                ["Results", "Experiments", "Evaluation"],
                ["Discussion", "Conclusion"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": False,
            "requires_data_availability": True,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "elsarticle",
    },
    "apa7": {
        "id": "apa7",
        "name": "APA 7th Edition Manuscript",
        "venue_code": "APA-7TH",
        "publisher": "APA",
        "version": "7.0",
        "last_updated": "2024-12-01",
        "provenance": "Publication Manual of the American Psychological Association 7th Ed.",
        "submission_layout": "Single-column double spaced",
        "camera_ready_layout": "Single-column double spaced",
        "constraints": {
            "page_limit": "venue_defined",
            "word_limit": 10000,
            "max_abstract_words": 250,
        },
        "review_policy": "single_blind",
        "supported_citation_styles": ["APA 7th (Author, Year)"],
        "structure_rules": {
            "required_sections": [
                "Abstract",
                "Introduction",
                ["Method", "Methods", "Methodology"],
                ["Results", "Findings"],
                ["Discussion", "Conclusion"],
                ["References", "Bibliography"],
            ],
            "optional_sections": ["Related Work"],
        },
        "metadata_rules": {
            "requires_keywords": True,
            "requires_ccs": False,
        },
        "export_rules": {
            "supports_pdf": True,
            "supports_latex": True,
            "supports_docx": True,
            "supports_bibtex": True,
            "supports_overleaf": True,
        },
        "latex_class": "article",
    },
}
